[config]
name = "DataGrip"
extends = "com.jetbrains.intellij"

[config.js]
module = '''
import buildHandler from 'dist/jetbrains.js';
export default buildHandler(
  import.meta,
  "/Applications/DataGrip.app/Contents/MacOS/datagrip"
)
'''
