[config]
name = "Paste (Setapp)"

[config.lua]
init = '''
local plist = require("plist")
local mac_keycode = require('mac_keycode')
local json = require('lunajson')
local data = plist.parse_file("~/Library/Preferences/com.wiheads.paste-setapp.plist")
function shortcut(property)
  local value = json.decode(data[1][property])
  local keys = mac_keycode.modifiers_to_strings(value.internalModifiers)
  table.insert(keys, mac_keycode.keycode_to_string(value.keyCode))
  tap(table.concat(keys, "+"))
end

'''

[chords]
"/v" = { name = "Paste", lua = "shortcut('kPSTPreferencesActivationShortcut')" }
"/vs" = { name = "Paste Stack", lua = "shortcut('paste-stack-shortcut')" }
