[config]
name = "Paste (Setapp)"

[on.hotkey]
file = "wiheads.js"
args = ["~/Library/Preferences/com.wiheads.paste-setapp.plist"]

[chords]
'/v' = { name = "Paste", 'emit:hotkey' = ['kPSTPreferencesActivationShortcut'] }
'/vs' = { name = "Paste Stack", 'emit:hotkey' = ['paste-stack-shortcut'] }
