name = "1Password"

[handler.hotkey]
type = "js"
file = "1password.js"
args = []

[chords]
'?/1' = { name = "1Password" }
'/1' = { name = "1Password: Quick Access", 'emit:hotkey' = ['quickAccess'] }
'/1s' = { name = "1Password: Show", 'emit:hotkey' = ['open'] }
'/1l' = { name = "1Password: Lock", 'emit:hotkey' = ['lock'] }
'/1a' = { name = "1Password: Autofill", 'emit:hotkey' = ['autoFill'] }

'?c' = { name = "Copy" }
ce = { name = "Copy Email", shortcut = "cmd+c" }
cu = { name = "Copy Username", shortcut = "cmd+c" }
cp = { name = "Copy Password", shortcut = "cmd+shift+c" }
co = { name = "Copy Onetime", shortcut = "opt+cmd+c" }
