[config]
name = "Rider"
extends = "com.jetbrains.intellij"

[config.js]
module = '''
import buildHandler from 'dist/jetbrains.js';
export default buildHandler(
  import.meta,
  "/Applications/Rider.app/Contents/MacOS/rider"
)
'''
