[config]
name = "PhpStorm"
extends = "com.jetbrains.intellij"

[config.js]
module = '''
import buildHandler from 'dist/jetbrains.js';
export default buildHandler(
  import.meta,
  "/Applications/PhpStorm.app/Contents/MacOS/phpstorm"
)
'''
