[config]
name = "CleanShot X (Setapp)"

[config.js]
init = '''
import {}
let shortcut = require('maketheweb_helpers').make_shortcut(
  "~/Library/Preferences/com.getcleanshot.app-setapp.plist",
)
'''

[chords]
"/c" = { name = "CleanShotX: All-In-One", js = "shortcut('LAVAtakeAllInOne')" }
"/cf" = { name = "CleanShotX: Fullscreen", js = "shortcut('LAVAtakeFullscreen')" }
"/co" = { name = "CleanShotX: OCR", js = "shortcut('LAVAtakeOCR')" }
"/col" = { name = "CleanShotX: OCR w/ Line Breaks", js = "shortcut('LAVAtakeOCR')" }
"/con" = { name = "CleanShotX: OCR No Line Breaks", js = "shortcut('LAVAtakeOCR')" }
"/ca" = { name = "CleanShotX: Area", js = "shortcut('LAVAstartGIFRecording')" }
"/cav" = { name = "CleanShotX: Area Previous", js = "shortcut('LAVAstartGIFRecording')" }
"/cs" = { name = "CleanShotX: Scrolling", js = "shortcut('LAVAscrollingCapture')" }
"/cv" = { name = "CleanShotX: Video Recording", js = "shortcut('LAVAstartVideoRecording')" }
"/cg" = { name = "CleanShotX: GIF Recording", js = "shortcut('LAVAstartGIFRecording')" }
