package = "chords"
version = "0.1.0"
lua = "==5.4" # This is the Lua version bundled with Chords

[description]
summary = ""
maintainer = "Leon Si"
labels = [ "" ]

[run]
args = ["src/playground.lua"]

[dependencies]
bplist-parser-lua = "0.1.1-1"
brace-expansion-lua = "0.1.0-1"
lunajson = "1.2.3-1"
penlight = "1.15.0-1"

[build]
type = "builtin"
