[config]
name = "Android Studio"
extends = "com.jetbrains.intellij"

[config.lua]
init = '''
action = require('jetbrains_helpers').create_action("/Applications/Android Studio.app/Contents/MacOS/studio")
'''
