[config]
name = "Android Studio"
extends = "com.jetbrains.intellij"

[config.js]
init = '''
import { createAction } from "dist/jetbrains.js";
export const action = createAction("/Applications/Android Studio.app/Contents/MacOS/studio")
'''
