[config]
name = "GoLand"
extends = "com.jetbrains.intellij"

[config.js]
module = '''
import { createAction } from 'dist/jetbrains.js';
export default createAction("/Applications/GoLand.app/Contents/MacOS/goland")
'''
