[config]
name = "Bartender"

[config.js]
module = '''
import buildHandler from 'dist/bartender.js';
export default buildHandler(
  import.meta,
  "~/Library/Preferences/com.surteesstudios.Bartender.plist"
)
'''

[chords]
'/-t' = { name = "Bartender: Toggle Hidden Items", args = [
  'shortcut',
  "KeyboardShortcuts_showHiddenItems",
] }
'/-s' = { name = "Bartender: Search", args = ['shortcut', "KeyboardShortcuts_quickSearch"] }
'/-h' = { name = "Bartender: Hide Left Application Menu", args = [
  'shortcut',
  "KeyboardShortcuts_hideLeftApplicationMenu",
] }
'/-a' = { name = "Bartender: Show All Items", args = [
  'shortcut',
  "KeyboardShortcuts_showAllItems",
] }

'-b' = { name = "Bar: Battery", args = [
  'item',
  'com.apple.controlcenter',
  'com.apple.controlcenter-Battery',
  'Battery',
] }
'-s' = { name = "Bar: Spotlight", args = [
  'item',
  'com.apple.controlcenter',
  'com.apple.Spotlight-Item-0',
  'Spotlight',
] }
'-c' = { name = "Bar: Clock", args = [
  'item',
  'com.apple.controlcenter',
  'com.apple.controlcenter-Clock',
  'Clock',
] }
'-cc' = { name = "Bar: Control Center", args = [
  'item',
  'com.apple.controlcenter',
  'com.apple.controlcenter-BentoBox-0',
  'Control Center',
] }
'-i' = { name = "Bar: Input", args = [
  'item',
  'com.apple.TextInputMenuAgent',
  'com.apple.TextInputMenuAgent-Item-0',
  'Text Input',
] }
'-w' = { name = "Bar: Wi-Fi", args = [
  'item',
  'com.apple.controlcenter',
  'com.apple.controlcenter-WiFi',
  'Wi-Fi',
] }
'-u' = { name = "Bar: User", args = [
  'item',
  'com.apple.controlcenter',
  'com.apple.controlcenter-UserSwitcher',
  'User',
] }
'-f' = { name = "Bar: Focus", args = [
  'item',
  'com.apple.controlcenter',
  'com.apple.controlcenter-FocusModes',
  'Focus',
] }

'-j' = { name = "Bar: JoyTap", args = [
  'item',
  'com.joytap.app-setapp',
  'com.joytap.app-setapp-Item-0',
  'JoyTap',
] }
