[config]
name = "Android Studio"
extends = "com.jetbrains.intellij"

[config.js]
module = '''
import buildHandler from "dist/jetbrains.js";
export default buildHandler(
  import.meta,
  "/Applications/Android Studio.app/Contents/MacOS/studio"
)
'''
