[config]
name = "RubyMine"
extends = "com.jetbrains.intellij"

[config.js]
module = '''
import buildHandler from 'dist/jetbrains.js';
export default buildHandler(
  import.meta,
  "/Applications/RubyMine.app/Contents/MacOS/rubymine"
)
'''
