[config]
name = "WebStorm"
extends = "com.jetbrains.intellij"

[config.js]
init = '''
import { createAction } from 'dist/jetbrains.js';
export const action = createAction("/Applications/WebStorm.app/Contents/MacOS/webstorm")
'''
