[config]
name = "RustRover"
extends = "com.jetbrains.intellij"

[config.lua]
init = '''
action = require('jetbrains_helpers').create_action("/Applications/RustRover.app/Contents/MacOS/rustrover")
'''
