[config]
name = "RustRover"
extends = "com.jetbrains.intellij"

[config.js]
init = '''
import { createAction } from 'dist/jetbrains.js';
export const action = createAction("/Applications/RustRover.app/Contents/MacOS/rustrover")
'''
