[config]
name = "WebStorm"
extends = "com.jetbrains.intellij"

[config.js]
module = '''
import buildHandler from 'dist/jetbrains.js';
export default buildHandler("/Applications/WebStorm.app/Contents/MacOS/webstorm")
'''
