[config]
name = "Bartender (Setapp)"
extends = "com.surteesstudios.Bartender"

[config.js]
module = '''
import buildHandler from 'dist/bartender.js';
export default buildHandler(
  import.meta,
  "~/Library/Preferences/com.surteesstudios.Bartender-setapp.plist"
)
'''
