[config]
name = "PixelSnap 2 (Setapp)"

[config.lua]
init = '''
local shortcut = require('maketheweb_helpers').make_shortcut(
  "~/Library/Preferences/pl.maketheweb.pixelsnap2-setapp.plist",
)
'''

[chords]
"/xc" = { name = "PixelSnap: Clear All", lua = "shortcut('LAVAclearAll')" }
"/x" = { name = "PixelSnap", lua = "shortcut('LAVAglobalHotkey')" }
