[config]
name = "PixelSnap 2 (Setapp)"

[config.js]
init = '''
import { makeShortcut } from 'dist/maketheweb.js';
const shortcut = makeShortcut(
  "~/Library/Preferences/pl.maketheweb.pixelsnap2-setapp.plist"
)
'''

[chords]
"/xc" = { name = "PixelSnap: Clear All", args = ['LAVAclearAll'] }
"/x" = { name = "PixelSnap", args = ['LAVAglobalHotkey'] }
