# @leonsilicon's custom global chords
[chords]
"/f" = { name = "Finder", shell = "open -a Finder" }
"/w" = { name = "Warp", command = "Open Warp", shell = "open -a 'Warp'" }
"/b" = { name = "Browser", command = "Open Browser", shell = """osascript -e 'tell application id "com.openai.atlas" to reopen'""" }
"/r" = { name = "Raycast", command = "Open Raycast", shell = "open -a 'Raycast'" }
