[config]
name = "GoLand"
extends = "com.jetbrains.intellij"

[config.js]
module = '''
import buildHandler from 'dist/jetbrains.js';
export default buildHandler(
  import.meta,
  "/Applications/GoLand.app/Contents/MacOS/goland"
)
'''
