[config]
name = "CleanShot X (Setapp)"

[config.js]
module = '''
import buildHandler from 'dist/maketheweb.js';
export default buildHandler(
  import.meta,
  "~/Library/Preferences/com.getcleanshot.app-setapp.plist",
);
'''

[chords]
"/c" = { name = "CleanShotX: All-In-One", args = ['LAVAtakeAllInOne'] }
"/cf" = { name = "CleanShotX: Fullscreen", args = ['LAVAtakeFullscreen'] }
"/co" = { name = "CleanShotX: OCR", args = ['LAVAtakeOCR'] }
"/col" = { name = "CleanShotX: OCR w/ Line Breaks", args = ['LAVAtakeOCR'] }
"/con" = { name = "CleanShotX: OCR No Line Breaks", args = ['LAVAtakeOCR'] }
# "/ca" = { name = "CleanShotX: Area", args = ['LAVAstartGIFRecording'] }
# "/ca[" = { name = "CleanShotX: Area Previous", args = ['LAVAstartGIFRecording'] }
"/cs" = { name = "CleanShotX: Scrolling", args = ['LAVAscrollingCapture'] }
"/cv" = { name = "CleanShotX: Video Recording", args = ['LAVAstartVideoRecording'] }
"/cg" = { name = "CleanShotX: GIF Recording", args = ['LAVAstartGIFRecording'] }
