name = "PixelSnap 2 (Setapp)"

[on.hotkey]
type = "js"
file = "maketheweb.js"
args = ["~/Library/Preferences/pl.maketheweb.pixelsnap2-setapp.plist"]

[chords]
'/xc' = { name = "PixelSnap: Clear All", 'emit:hotkey' = ['LAVAclearAll'] }
'/x' = { name = "PixelSnap", 'emit:hotkey' = ['LAVAglobalHotkey'] }
