# https://support.google.com/chrome/answer/157179 > Mac
[config]
name = "Chromium Base Shortcuts"

[chords]
# Window
'?w' = { name = "Window" }
wn = { name = "Window: New", command = "Open a new window", shortcut = "cmd+n" }
wi = { name = "Window: Incognito", command = "Open a new window in Incognito mode", shortcut = "cmd+shift+n" }
wc = { name = "Window: Close", command = "Close the current window", shortcut = "cmd+shift+w" }
wm = { name = "Window: Minimize", command = "Minimize the window", shortcut = "cmd+m" }
wh = { name = "Window: Hide", command = "Hide Google Chrome", shortcut = "cmd+h" }
wq = { name = "Window: Quit", command = "Quit Google Chrome", shortcut = "cmd+q" }

# Tab
'?t' = { name = "Tab" }
tq = { name = "Tab: Quit", command = "Close the current tab, or pop-up", shortcut = "cmd+w" }
tn = { name = "Tab: New", command = "Open a new tab, and jump to it", shortcut = "cmd+t" }
to = { name = "Tab: Reopen", command = "Reopen previously closed tabs in the order they were closed", shortcut = "cmd+shift+t" }
't]' = { name = "Tab: Next", command = "Jump to the next open tab", shortcut = "ctrl+tab" }
't[' = { name = "Tab: Previous", command = "Jump to the previous open tab", shortcut = "cmd+shift+tab" }
t1 = { name = "Tab 1", command = "Jump to a specific tab", shortcut = "cmd+1" }
t2 = { name = "Tab 2", command = "Jump to a specific tab", shortcut = "cmd+2" }
t3 = { name = "Tab 3", command = "Jump to a specific tab", shortcut = "cmd+3" }
t4 = { name = "Tab 4", command = "Jump to a specific tab", shortcut = "cmd+4" }
t5 = { name = "Tab 5", command = "Jump to a specific tab", shortcut = "cmd+5" }
t6 = { name = "Tab 6", command = "Jump to a specific tab", shortcut = "cmd+6" }
t7 = { name = "Tab 7", command = "Jump to a specific tab", shortcut = "cmd+7" }
t8 = { name = "Tab 8", command = "Jump to a specific tab", shortcut = "cmd+8" }
tl = { name = "Tab: Left Move", command = "Move tabs right or left", shortcut = "cmd+shift+pgup" }
tr = { name = "Tab: Right Move", command = "Move tabs right or left", shortcut = "cmd+shift+pgdown" }

# History
'?h' = { name = "History" }
hb = { name = "History: Back", command = "Open the next page from your browsing history in the current tab", shortcut = "cmd+]" }
hf = { name = "History: Forward", command = "Open the previous page from your browsing history in the current tab", shortcut = "cmd+[" }

# Pages
'?p' = { name = "Page" }
'p,' = { name = "Page: Settings", command = "Open the Settings page in a new tab", shortcut = "cmd+," }
ph = { name = "Page: History", command = "Open the History page in a new tab", shortcut = "cmd+y" }
pd = { name = "Page: Downloads", command = "Open the Downloads page in a new tab", shortcut = "cmd+shift+j" }
pm = { name = "Page: Home", command = "Open your home page in the current tab", shortcut = "cmd+shift+h" }
psd = { name = "Page Setup Dialog", command = "Open the Page Setup dialog", shortcut = "cmd+option+p" }
ps = { name = "Page: Save", command = "Open options to save the current page", shortcut = "cmd+s" }

# Matches
'?m' = { name = "Match" }
'm]' = { name = "Match: Next", command = "Jump to the next match to your Find Bar search", shortcut = "cmd+g" }
'm[' = { name = "Match: Previous", command = "Jump to the previous match to your Find Bar search", shortcut = "cmd+shift+g" }

# Bookmarks
'?b' = { name = "Bookmarks" }
bt = { name = "Bookmarks: Toggle", command = "Show or hide the Bookmarks Bar", shortcut = "cmd+b" }
bm = { name = "Bookmarks: Manager", command = "Open the Bookmark Manager", shortcut = "cmd+option+b" }
bs = { name = "Bookmark: Save", command = "Save your current webpage as a bookmark", shortcut = "cmd+d" }
bf = { name = "Bookmarks: Folder from tabs", command = "Save all open tabs as bookmarks in a new folder", shortcut = "cmd+shift+d" }

# Zoom
'?z' = { name = "Zoom" }
zi = { name = "Zoom In", command = "Make everything on the page bigger", shortcut = "cmd+plus" }
zo = { name = "Zoom Out", command = "Make everything on the page smaller", shortcut = "cmd+minus" }
zr = { name = "Zoom Reset", command = "Return everything on the page to the default size", shortcut = "cmd+0" }

# Load
'?l' = { name = "Load" }
lr = { name = "Load: Reload", command = "Reload your current page", shortcut = "cmd+r" }
lh = { name = "Load: Hard Reload", command = "Reload your current page, ignoring cached content", shortcut = "cmd+shift+r" }
ls = { name = "Load: Stop", command = "Stop the page loading", shortcut = "esc" }

# Goto
'?g' = { name = "Goto" }
ga = { name = "Goto: Account", command = "Log in as a different user, browse as a Guest, or access payment and password info", shortcut = "cmd+shift+m" }
gb = { name = "Goto: Bar", command = "Jump to the address bar", shortcut = "cmd+l" }
gm = { name = "Goto: Main Menu", command = "Jump to the main menu bar", shortcut = "control+f2" }

fs = { name = "Full Screen", command = "Turn on full-screen mode", shortcut = "fn+f" }
fso = { name = "Full Screen Off", command = "Turn off full-screen mode", shortcut = "fn+f" }
dt = { name = "Developer Tools", command = "Open Developer Tools", shortcut = "cmd+option+i" }
odb = { name = "Open Delete Browsing Data", command = "Open the Delete Browsing Data options", shortcut = "cmd+shift+delete" }
'fd]' = { name = "Focus Dialog Next", command = "Cycle focus to unfocused dialog (if showing) and all toolbars", shortcut = "cmd+option+up" }
'fd[' = { name = "Focus Dialog Previous", command = "Cycle focus to unfocused dialog (if showing) and all toolbars", shortcut = "cmd+option+down" }
ofb = { name = "Open Feedback", command = "Open a feedback form", shortcut = "cmd+option+shift+i" }
cb = { name = "Caret Browsing", command = "Turn on caret browsing", shortcut = "f7" }
fid = { name = "Focus Inactive Dialogs", command = "Focus on inactive dialogs", shortcut = "cmd+option+shift+a" }
sp = { name = "Split View", command = "Open split view in the active tab", shortcut = "cmd+option+n" }
rp = { name = "Remove Predictions", command = "Remove predictions from your address bar", shortcut = "shift+fn+delete" }
cab = { name = "Cursor to Address Bar", command = "Move cursor to the address bar", shortcut = "control+f5" }
ne = { name = "New Email", command = "Compose a new email message with a link to the current page", shortcut = "cmd+shift+i" }
pr = { name = "Print", command = "Open options to print the current page", shortcut = "cmd+p" }

of = { name = "Open File", command = "Open a file from your computer", shortcut = "cmd+o" }
sc = { name = "Source Code", command = "Display non-editable HTML source code for the current page", shortcut = "cmd+option+u" }
jc = { name = "JavaScript Console", command = "Open the JavaScript Console", shortcut = "cmd+option+j" }
sd = { name = "Scroll Down", command = "Scroll down a webpage, a screen at a time", shortcut = "space" }
su = { name = "Scroll Up", command = "Scroll up a webpage, a screen at a time", shortcut = "shift+space" }
sw = { name = "Search Web", command = "Search the web", shortcut = "cmd+option+f" }
